app:
  name: video-service
  replicas: 1
  port: 3003
domain: dev-valhall.kebert.se
image:
  repository: ghcr.io/kebertr/valhall-video-api
  tag: dev-f7e4a74
database:
  host: video-postgres-service
  port: 5432
  secretName: video-postgres-credentials-dev
migration:
  enabled: true
  command: "pnpm --filter videos-api exec prisma migrate deploy"
minio:
  endpoint: minio-service.minio.svc.cluster.local
  port: 9000
  useSSL: "false"
  bucket: valhall-videos-dev
  secretName: video-minio-credentials-dev
keycloak:
  url: https://auth.kebert.se
  realm: valhall
  clientId: valhall-api-dev
grpc:
  memberUrl: member-service:50051