app:
  name: member-service
  replicas: 1
  port: 3002
domain: dev-valhall.kebert.se
image:
  repository: ghcr.io/kebertr/valhall-member-api
  tag: dev-4d2dae0
database:
  host: postgres-service
  port: 5432
  secretName: postgres-credentials
migration:
  enabled: true
  command: "npx prisma migrate deploy"
