app:
  name: video-postgres
  statefulSetName: video-postgres-statefulset
  serviceName: video-postgres-service
  internalServiceName: video-postgresql-internal
  configMapName: video-postgres-config
  tailscaleHostname: video-postgres-dev

StorageClassName: local-path
Timezone: "Europe/Stockholm"

DBSecretName: video-postgres-credentials
DBImage: postgres:16
DBResourceLimit: true
DBCPU: "1000m"
DBMemory: "1000Mi"
DBStorage: 10Gi
