apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.app.name }}-migration"
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: prisma-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always

          command:
            - sh
            - -c
            - {{ .Values.migration.command | quote }}

          env:
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}

            - name: DB_PORT
              value: {{ .Values.database.port | quote }}

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_DB

            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?schema=public"
