apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cloudflared
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Kebertr/homeserver.git
    targetRevision: main
    path: helm_charts/cloudflare

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true