apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.98.4
    chart: tailscale-operator

    helm:
      values: |
        operatorConfig:
          defaultTags:
            - "tag:k8s"
        proxyConfig:
          defaultTags: "tag:k8s"
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
