runnerScaleSetName: homeserver-gitops

githubConfigUrl: https://github.com/Kebertr/homeserver-gitops

githubConfigSecret: github-runner-sec

minRunners: 0
maxRunners: 1

controllerServiceAccount:
  namespace: arc
  name: action-runner-controller-gha-rs-controller