runnerScaleSetName: homeserver

githubConfigUrl: https://github.com/Kebertr/homeserver

githubConfigSecret: github-runner-sec

minRunners: 1
maxRunners: 1

controllerServiceAccount:
  namespace: arc
  name: action-runner-controller-gha-rs-controller