apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentel-collector

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: opentelemetry

  template:
    metadata:
      labels:
        app: opentelemetry

    spec:
      containers:
        - name: opentel-collector

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          args:
            - "--config=/etc/opentelcol/config.yaml"

          ports:
            - name: otlp-grpc
              containerPort: 4317

            - name: otlp-http
              containerPort: 4318

          volumeMounts:
            - name: config
              mountPath: /etc/opentelcol

      volumes:
        - name: config
          configMap:
            name: opentel-collector-conf