apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: valhall-watcher
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: newest-build

  applicationRefs:
    - namePattern: frontend-valhall
      images:
        - alias: frontend
          imageName: ghcr.io/kebertr/valhall-frontend:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^prod-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: main
          writeBackTarget: helmvalues:/helm_charts/frontend-valhall/values-prod.yaml
          pullRequest:
            github: {}

    - namePattern: frontend-valhall-dev
      images:
        - alias: frontend
          imageName: ghcr.io/kebertr/valhall-frontend:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^dev-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: dev
          writeBackTarget: helmvalues:/helm_charts/frontend-valhall/values-dev.yaml

    - namePattern: bong-api
      images:
        - alias: bong-api
          imageName: ghcr.io/kebertr/valhall-bong-api:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^prod-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: main
          writeBackTarget: helmvalues:/helm_charts/backend-valhall/bong-valhall/values-prod.yaml
          pullRequest:
            github: {}

    - namePattern: bong-api-dev
      images:
        - alias: bong-api
          imageName: ghcr.io/kebertr/valhall-bong-api:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^dev-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: dev
          writeBackTarget: helmvalues:/helm_charts/backend-valhall/bong-valhall/values-dev.yaml

    - namePattern: member-api
      images:
        - alias: member-api
          imageName: ghcr.io/kebertr/valhall-member-api:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^prod-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: main
          writeBackTarget: helmvalues:/helm_charts/backend-valhall/member-valhall/values-prod.yaml
          pullRequest:
            github: {}

    - namePattern: member-api-dev
      images:
        - alias: member-api
          imageName: ghcr.io/kebertr/valhall-member-api:latest
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: "regexp:^dev-.+$"
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      writeBackConfig:
        method: git:secret:argocd/image-updater-git-creds
        gitConfig:
          repository: https://github.com/Kebertr/homeserver-gitops.git
          branch: dev
          writeBackTarget: helmvalues:/helm_charts/backend-valhall/member-valhall/values-dev.yaml
