apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api-tailscale
  namespace: minio
  annotations:
    tailscale.com/hostname: "ingress-api"
spec:
  ingressClassName: tailscale

  defaultBackend:
    service:
      name: minio-service
      port:
        number: 9000