runnerScaleSetName: valhall

githubConfigUrl: https://github.com/Kebertr/valhall

githubConfigSecret: github-runner-sec

minRunners: 1
maxRunners: 2

controllerServiceAccount:
  namespace: arc
  name: action-runner-controller-gha-rs-controller