apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  annotations:
    tailscale.com/hostname: "bong-postgres"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432