apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  annotations:
    tailscale.com/hostname: {{ .Values.app.tailscaleHostname | quote }}
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
