app:
  name: member-postgres
  statefulSetName: member-postgres-statefulset
  serviceName: member-postgres-service
  internalServiceName: member-postgresql-internal
  configMapName: member-postgres-config
  tailscaleHostname: member-postgres

StorageClassName: local-path
Timezone: "Europe/Stockholm"

DBSecretName: member-postgres-credentials
DBImage: postgres:16
DBResourceLimit: true
DBCPU: "200m"
DBMemory: 1Gi
DBStorage: 20Gi

