app:
  name: bong-postgres
  statefulSetName: bong-postgres-statefulset
  serviceName: bong-postgres-service
  internalServiceName: bong-postgresql-internal
  configMapName: bong-postgres-config
  tailscaleHostname: bong-postgres

StorageClassName: local-path
Timezone: "Europe/Stockholm"

DBSecretName: bong-postgres-credentials
DBImage: postgres:16
DBResourceLimit: true
DBCPU: "200m"
DBMemory: 1Gi
DBStorage: 20Gi
