app:
  name: bong-postgres
  statefulSetName: bong-postgres-statefulset
  serviceName: bong-postgres-service
  internalServiceName: bong-postgresql-internal
  configMapName: bong-postgres-config
  tailscaleHostname: bong-postgres-dev

StorageClassName: local-path
Timezone: "Europe/Stockholm"

DBSecretName: bong-postgres-credentials-dev
DBImage: postgres:16
DBResourceLimit: true
DBCPU: "100m"
DBMemory: "256Mi"
DBStorage: 1Gi
