app:
  name: frontend
  replicas: 1
domain: dev-valhall.kebert.se
environment: Development
message: "Frontend Dev Environment"
image:
  repository: ghcr.io/kebertr/valhall-frontend
  tag: dev-ee82d19
api:
  serviceName: bong-service
