app:
  name: frontend
  replicas: 1
domain: valhall.kebert.se
environment: Production
message: "Frontend Prod Environment"
image:
  repository: ghcr.io/kebertr/valhall-frontend
  tag: prod-6d270b1
api:
  serviceName: penalty-service
