app:
  name: bong-service
  replicas: 1
  port: 3001
domain: dev-valhall.kebert.se
image:
  repository: ghcr.io/kebertr/valhall-bong-api
  tag: dev-f7e4a74
database:
  host: bong-postgres-service
  port: 5432
  secretName: bong-postgres-credentials-dev
migration:
  enabled: true
  command: "pnpm --filter bong-api exec prisma migrate deploy"
