app:
  name: bong-service
  replicas: 1
  port: 3001
domain: dev-valhall.kebert.se
image:
  repository: ghcr.io/kebertr/valhall-bong-api
  tag: dev-e721ef0
database:
  host: bong-postgres-service
  port: 5432
  secretName: bong-postgres-credentials
migration:
  enabled: true
  command: "npx prisma migrate deploy"
