apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-member-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kebertr/homeserver-gitops.git
    targetRevision: dev
    path: helm_charts/database-valhall/member
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: valhall-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
