apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: PORT
              value: {{ .Values.app.port | quote }}
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName | quote }}
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?schema=public"
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint | quote }}
            - name: MINIO_PORT
              value: {{ .Values.minio.port | quote }}
            - name: MINIO_USE_SSL
              value: {{ .Values.minio.useSSL | quote }}
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | quote }}
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName | quote }}
                  key: MINIO_SECRET_KEY
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.realm | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.clientId | quote }}
            - name: MEMBER_GRPC_URL
              value: {{ .Values.grpc.memberUrl | quote }}
            - name: FRONTEND_URL
              value: {{ .Values.frontendUrl | quote }}