# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.app.port}}
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.app.port }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: {{ .Values.grpc.port }}
  type: ClusterIP
