StorageClassName: local-path 
Timezone: "Europe/Stockholm"

MinioImage: quay.io/minio/minio
MinioTag: latest

MinioResourceLimit: true
MinioCPU: "1000m"
MinioMemory: "1000Mi"

MinioApiDomain: "upload.kebert.se"
MinioApiTlsSecret: "upload-kebert-se-tls"
MinioPublicBucketProd: "valhall-videos"
MinioPublicBucketDev: "valhall-videos-dev"
MinioProfileBucketProd: "valhall-profiles"
MinioProfileBucketDev: "valhall-profiles-dev"

MinioApiTailscaleHostname: "minio-api"
MinioConsoleHostname: "minio-console"
