StorageClassName: local-path 
Timezone: "Europe/Stockholm"

MinioImage: quay.io/minio/minio
MinioTag: latest

MinioStorage: 20Gi

MinioResourceLimit: true
MinioCPU: "1000m"
MinioMemory: "1000Mi"

MinioApiDomain: "uploads.kebert.se"
MinioApiTlsSecret: "uploads-kebert-se-tls"
MinioPublicBucket: "valhall-redemptions"

MinioConsoleHostname: "minio-console"